# Generated by Django 4.2.21 on 2025-05-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=64)),
                ('task_id', models.CharField(max_length=64, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PDFReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=64)),
                ('task_id', models.CharField(max_length=64, unique=True)),
                ('pdf_file', models.FileField(upload_to='pdf_reports/')),
            ],
        ),
    ]
